version: '3.8'

services:
  api:
    image: bitnami/laravel:latest
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - tradeup
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tradeup

  front-vue:
    build:
      context: ./front-vue
      dockerfile: Dockerfile
    container_name: front-vue
    restart: unless-stopped
    networks:
      - tradeup
    ports:
      - "8080:8080"
    depends_on:
      - api

networks:
  tradeup:
    driver: bridge

volumes:
  db-data:
